package fr.byob.bs.model.utilisateur;
// Generated 27 févr. 2009 10:34:58 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import fr.byob.bs.model.Photo;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name = "PHOTO_UTILISATEUR")
public class PhotoUtilisateur extends Photo implements java.io.Serializable {

	private static final long serialVersionUID = -3690095955179405069L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "idPhotoUtilisateurGenerator")
	@GenericGenerator(name = "idPhotoUtilisateurGenerator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = { @Parameter(name = "initial_value", value = "100"),
			@Parameter(name = "sequence_name", value = "id_photo_utilisateur_sequence") })
	@Column(name = "ID_PHOTO", unique = true, nullable = false)
	private Long idPhoto;
	
	
	public PhotoUtilisateur() { 
	}

	public PhotoUtilisateur(String path) {
		super(path);
	}
	
	private PhotoUtilisateur(Long idPhoto, String path, boolean tmp, String fullPath, String filePath) {
		super(path, tmp, fullPath, filePath);
		this.idPhoto = idPhoto;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idPhoto == null) ? 0 : idPhoto.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PhotoUtilisateur other = (PhotoUtilisateur) obj;
		if (idPhoto == null) {
			if (other.idPhoto != null)
				return false;
		} else if (!idPhoto.equals(other.idPhoto))
			return false;
		return true;
	}

	public Long getIdPhoto() {
		return this.idPhoto;
	}

	public void setIdPhoto(Long idPhoto) {
		this.idPhoto = idPhoto;
	}

	@Override
	public Photo clone() {
		return new PhotoUtilisateur(getIdPhoto(), getPath(), getIsTMP(), getFullPath(), getFilePath());
	}
}
