package fr.byob.bs.model;
// Generated 27 févr. 2009 10:34:58 by Hibernate Tools 3.2.2.GA


/**
 * TypeNav generated by hbm2java
 */
public enum TypeNav {
	COTIERE,
	HAUTURIERE, CABOTAGE, CONVOYAGE, COURSE
}
