package fr.byob.bs.model.experience;

// Generated 27 févr. 2009 10:34:58 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import fr.byob.bs.model.TypeDuree;
import fr.byob.bs.model.TypePoste;
import fr.byob.bs.model.bateau.TypeCoque;
import fr.byob.bs.model.utilisateur.Utilisateur;

/**
 * Xp generated by hbm2java
 */
@Entity
@Table(name = "XP")
public class Xp implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "idXpGenerator")
	@GenericGenerator(name = "idXpGenerator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = { @Parameter(name = "initial_value", value = "100"),
			@Parameter(name = "sequence_name", value = "id_xp_sequence") })
	@Column(name = "ID_XP", unique = true, nullable = false)
	private Long idXp;

	@Enumerated(EnumType.STRING)
	@Column(name = "TYPE_XP", nullable = false)
	@NotNull
	private TypeXp typeXp;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UTILISATEUR", nullable = false)
	@NotNull
	private Utilisateur utilisateur;

	@Enumerated(EnumType.STRING)
	@Column(name = "POSTE_OCCUPE", nullable = true)
	private TypePoste typePoste;

	@Enumerated(EnumType.STRING)
	@Column(name = "TYPE_DUREE", nullable = false)
	@NotNull
	private TypeDuree typeDuree;

	@Enumerated(EnumType.STRING)
	@Column(name = "TYPE_COQUE", nullable = true)
	private TypeCoque typeCoque;

	@Column(name = "TITRE", nullable = false)
	@NotNull
	@Length(max = 255)
	private String titre;

	@Column(name = "DUREE", nullable = false)
	@NotNull
	private Integer duree;

	@Column(name = "DESCRIPTION")
	@Length(max = 500)
	private String description;

	public Xp() {
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idXp == null) ? 0 : idXp.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Xp other = (Xp) obj;
		if (idXp == null) {
			if (other.idXp != null)
				return false;
		} else if (!idXp.equals(other.idXp))
			return false;
		return true;
	}

	public Long getIdXp() {
		return this.idXp;
	}

	public void setIdXp(Long idXp) {
		this.idXp = idXp;
	}

	public TypeXp getTypeXp() {
		return this.typeXp;
	}

	public void setTypeXp(TypeXp typeXp) {
		this.typeXp = typeXp;
	}

	public Utilisateur getUtilisateur() {
		return utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public TypePoste getTypePoste() {
		return this.typePoste;
	}

	public void setTypePoste(TypePoste typePoste) {
		this.typePoste = typePoste;
	}

	public TypeDuree getTypeDuree() {
		return this.typeDuree;
	}

	public void setTypeDuree(TypeDuree typeDuree) {
		this.typeDuree = typeDuree;
	}

	public TypeCoque getTypeCoque() {
		return this.typeCoque;
	}

	public void setTypeCoque(TypeCoque typeCoque) {
		this.typeCoque = typeCoque;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public Integer getDuree() {
		return this.duree;
	}

	public void setDuree(Integer duree) {
		this.duree = duree;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String desciption) {
		this.description = desciption;
	}
}
