package fr.byob.bs.model.experience;
// Generated 27 févr. 2009 10:34:58 by Hibernate Tools 3.2.2.GA


/**
 * XpGenerale generated by hbm2java
 */
public enum XpGenerale {
	INEXPERIMENTE,
	NOVICE,
	CONFIRME,
	EXPERIMENTE,
	PROFESSIONNEL
}