package fr.byob.bs.model.annonce;
// Generated 27 févr. 2009 10:34:58 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

import fr.byob.bs.model.Lieu;
import fr.byob.bs.model.TypeDuree;

/**
 * Escale generated by hbm2java
 */
@Entity
@Table(name = "ESCALE")
public class Escale implements java.io.Serializable, Comparable<Escale> {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "idEscaleGenerator")
	@GenericGenerator(name = "idEscaleGenerator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = { @Parameter(name = "initial_value", value = "100"),
			@Parameter(name = "sequence_name", value = "id_escale_sequence") })
	@Column(name = "ID_ESCALE", unique = true, nullable = false)
	private Integer idEscale;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LIEU", nullable = false)
	@NotNull 
	private Lieu lieu;
	
	@Enumerated(EnumType.STRING)
	@Column(name = "TYPE_DUREE", nullable = true)
	private TypeDuree typeDuree;
	
	@Column(name = "DUREE")
	private Integer duree;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", length = 8, nullable = false)
	@NotNull
	private Date date;
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OFFRE", nullable = false)
	@NotNull
	private Offre offre;

	public Escale() {
		lieu = new Lieu();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idEscale == null) ? 0 : idEscale.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Escale other = (Escale) obj;
		if (idEscale == null) {
			if (other.idEscale != null)
				return false;
		} else if (!idEscale.equals(other.idEscale))
			return false;
		return true;
	}

	public Integer getIdEscale() {
		return this.idEscale;
	}

	public void setIdEscale(Integer idEscale) {
		this.idEscale = idEscale;
	}

	public Lieu getLieu() {
		return this.lieu;
	}

	public void setLieu(Lieu lieu) {
		this.lieu = lieu;
	}

	public TypeDuree getTypeDuree() {
		return this.typeDuree;
	}

	public void setTypeDuree(TypeDuree typeDuree) {
		this.typeDuree = typeDuree;
	}


	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}


	public Integer getDuree() {
		return this.duree;
	}

	public void setDuree(Integer duree) {
		this.duree = duree;
	}
	
	public Offre getOffre() {
		return this.offre;
	}

	public void setOffre(Offre offre) {
		this.offre = offre;
	}

	 @Override
	public int compareTo(Escale escale) {
		return this.date.compareTo(escale.getDate());
	}

}
