package fr.byob.bs.model.bateau;
// Generated 27 févr. 2009 10:34:58 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.Max;
import org.hibernate.validator.Min;
import org.hibernate.validator.NotNull;

/**
 * EquipGeneralHasEquipement generated by hbm2java
 */
@Entity
@Table(name = "EQUIP_GENERAL_HAS_EQUIPEMENT")
public class EquipGeneralHasEquipement implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "equipGeneral", column = @Column(name = "EQUIP_GENERAL", nullable = false)),
			@AttributeOverride(name = "equipement", column = @Column(name = "EQUIPEMENT", nullable = false))})
	@NotNull
	private EquipGeneralHasEquipementId id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EQUIP_GENERAL", nullable = false, insertable = false, updatable = false)
	@NotNull
	private EquipGeneral equipGeneral;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EQUIPEMENT", nullable = false, insertable = false, updatable = false)
	@NotNull
	private Equipement equipement;
	
	@Column(name = "NOMBRE")
	@NotNull
	@Min(0)
	@Max(10)
	private Integer nombre;

	public EquipGeneralHasEquipement() {
	}

	public EquipGeneralHasEquipement(EquipGeneralHasEquipementId id,
			EquipGeneral equipGeneral, Equipement equipement) {
		this.id = id;
		this.equipGeneral = equipGeneral;
		this.equipement = equipement;
	}
	public EquipGeneralHasEquipement(EquipGeneralHasEquipementId id,
			EquipGeneral equipGeneral, Equipement equipement, Integer nombre) {
		this.id = id;
		this.equipGeneral = equipGeneral;
		this.equipement = equipement;
		this.nombre = nombre;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EquipGeneralHasEquipement other = (EquipGeneralHasEquipement) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
	public EquipGeneralHasEquipementId getId() {
		return this.id;
	}

	public void setId(EquipGeneralHasEquipementId id) {
		this.id = id;
	}
	
	public EquipGeneral getEquipGeneral() {
		return this.equipGeneral;
	}

	public void setEquipGeneral(EquipGeneral equipGeneral) {
		this.equipGeneral = equipGeneral;
	}

	public Equipement getEquipement() {
		return this.equipement;
	}

	public void setEquipement(Equipement equipement) {
		this.equipement = equipement;
	}

	public Integer getNombre() {
		return this.nombre;
	}

	public void setNombre(Integer nombre) {
		this.nombre = nombre;
	}

}
