package fr.byob.bs.model.bateau;
// Generated 27 févr. 2009 10:34:58 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.hibernate.validator.NotNull;

/**
 * EquipGeneralHasEquipementId generated by hbm2java
 */
@Embeddable
public class EquipGeneralHasEquipementId implements java.io.Serializable {

	private static final long serialVersionUID = 3935869324531219590L;

	private Long equipGeneral;
	private long equipement;

	public EquipGeneralHasEquipementId() {
	}

	public EquipGeneralHasEquipementId(Long equipGeneral, long equipement) {
		this.equipGeneral = equipGeneral;
		this.equipement = equipement;
	}

	@Column(name = "EQUIP_GENERAL", nullable = false)
	@NotNull
	public Long getEquipGeneral() {
		return this.equipGeneral;
	}

	public void setEquipGeneral(Long equipGeneral) {
		this.equipGeneral = equipGeneral;
	}

	@Column(name = "EQUIPEMENT", nullable = false)
	@NotNull
	public long getEquipement() {
		return this.equipement;
	}

	public void setEquipement(long equipement) {
		this.equipement = equipement;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		if (equipGeneral != null) {
			result = prime * result
					+ (int) (equipGeneral ^ (equipGeneral >>> 32));
		}
		result += prime * result + (int) (equipement ^ (equipement >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EquipGeneralHasEquipementId other = (EquipGeneralHasEquipementId) obj;
		if (!equipGeneral.equals(other.equipGeneral))
			return false;
		if (equipement != other.equipement)
			return false;
		return true;
	}

}
