package fr.byob.bs.model.bateau;

// Generated 27 févr. 2009 10:34:58 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Equipement generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(mutable=false)
@Table(name = "EQUIPEMENT")
public class Equipement implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long idEquipement;
	private String libelle;
	private Set<EquipGeneralHasEquipement> equipGeneralHasEquipements = new HashSet<EquipGeneralHasEquipement>(
			0);
	private TypeEquipement typeEquipement;

	public Equipement() {
	}

	public Equipement(String libelle) {
		this.libelle = libelle;
	}

	public Equipement(String libelle,
			Set<EquipGeneralHasEquipement> equipGeneralHasEquipements) {
		this.libelle = libelle;
		this.equipGeneralHasEquipements = equipGeneralHasEquipements;
	}

	public Equipement(String libelle,
			Set<EquipGeneralHasEquipement> equipGeneralHasEquipements,
			TypeEquipement typeEquipement) {
		this.libelle = libelle;
		this.equipGeneralHasEquipements = equipGeneralHasEquipements;
		this.typeEquipement = typeEquipement;
	}

	@Id
	@Column(name = "ID_EQUIPEMENT", unique = true, nullable = false)
	public Long getIdEquipement() {
		return this.idEquipement;
	}

	public void setIdEquipement(Long idEquipement) {
		this.idEquipement = idEquipement;
	}

	@Column(name = "LIBELLE", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "equipement")
	public Set<EquipGeneralHasEquipement> getEquipGeneralHasEquipements() {
		return this.equipGeneralHasEquipements;
	}

	public void setEquipGeneralHasEquipements(
			Set<EquipGeneralHasEquipement> equipGeneralHasEquipements) {
		this.equipGeneralHasEquipements = equipGeneralHasEquipements;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "TYPE_EQUIPEMENT", nullable = false)
	public TypeEquipement getTypeEquipement() {
		return typeEquipement;
	}

	public void setTypeEquipement(TypeEquipement typeEquipement) {
		this.typeEquipement = typeEquipement;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idEquipement == null) ? 0 : idEquipement.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Equipement other = (Equipement) obj;
		if (idEquipement == null) {
			if (other.idEquipement != null)
				return false;
		} else if (!idEquipement.equals(other.idEquipement))
			return false;
		return true;
	}


}
